add images
Lordik10032018/TeamProjectGo pull request #4
Opened 2024-03-21 21:21 UTC by KyrykS

2024-03-21 22:48 UTC, KyrykS commented
Привіт! трохи вийшло багато комітів, бо мені виглядало, що не зберегло пул-реквест. Наступного разу буду уважніша)

2024-03-22 11:30 UTC, Lordik10032018 requested changes
Привіт, відправив тобі в slack відео.

2024-03-22 13:53 UTC, KyrykS commented
Привіт, відкорегувала html, подивися будь ласка. Я тільки першого разу створила пул-реквест, а далі вже йдуть як коміти. Так має бути?Дякую)

2024-03-24 09:46 UTC, Lordik10032018 requested changes
Відправив відео в Slack.

2024-03-25 09:27 UTC, Lordik10032018 requested changes
Написав в Slack.

2024-03-26 08:52 UTC, Lordik10032018 approved these changes

2024-03-26 08:52 UTC, merged